package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "cqemsbusinessSoap", targetNamespace = "http://tempuri.org/")
public interface CqemsbusinessSoap {

	/**
	 * 接收电商信息
	 * 
	 * @param emscode
	 * @param xmlstring
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "cqems_electronic_business", action = "http://tempuri.org/cqems_electronic_business")
	@WebResult(name = "cqems_electronic_businessResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "cqems_electronic_business", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsElectronicBusiness")
	@ResponseWrapper(localName = "cqems_electronic_businessResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsElectronicBusinessResponse")
	public String cqemsElectronicBusiness(
			@WebParam(name = "xmlstring", targetNamespace = "http://tempuri.org/") String xmlstring,
			@WebParam(name = "emscode", targetNamespace = "http://tempuri.org/") String emscode);

	/**
	 * 取消申报
	 * 
	 * @param emscode
	 * @param originalORDERNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "cqems_del", action = "http://tempuri.org/cqems_del")
	@WebResult(name = "cqems_delResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "cqems_del", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsDel")
	@ResponseWrapper(localName = "cqems_delResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsDelResponse")
	public String cqemsDel(
			@WebParam(name = "ORIGINAL_ORDER_NO", targetNamespace = "http://tempuri.org/") String originalORDERNO,
			@WebParam(name = "emscode", targetNamespace = "http://tempuri.org/") String emscode);

	/**
	 * 获取申报状态
	 * 
	 * @param emscode
	 * @param originalORDERNO
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "cqems_type", action = "http://tempuri.org/cqems_type")
	@WebResult(name = "cqems_typeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "cqems_type", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsType")
	@ResponseWrapper(localName = "cqems_typeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsTypeResponse")
	public String cqemsType(
			@WebParam(name = "ORIGINAL_ORDER_NO", targetNamespace = "http://tempuri.org/") String originalORDERNO,
			@WebParam(name = "emscode", targetNamespace = "http://tempuri.org/") String emscode);

	/**
	 * 接收电商信息含运单
	 * 
	 * @param emscode
	 * @param xmlstring
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "cqems_electronic_business_all", action = "http://tempuri.org/cqems_electronic_business_all")
	@WebResult(name = "cqems_electronic_business_allResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "cqems_electronic_business_all", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsElectronicBusinessAll")
	@ResponseWrapper(localName = "cqems_electronic_business_allResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CqemsElectronicBusinessAllResponse")
	public String cqemsElectronicBusinessAll(
			@WebParam(name = "xmlstring", targetNamespace = "http://tempuri.org/") String xmlstring,
			@WebParam(name = "emscode", targetNamespace = "http://tempuri.org/") String emscode);

}
