package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * cqemsbusiness service = new cqemsbusiness();
 * CqemsbusinessSoap portType = service.getCqemsbusinessSoap();
 * portType.cqemsElectronicBusiness(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "cqemsbusiness", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://115.28.134.167/cqemsbusiness.asmx?WSDL")
public class Cqemsbusiness extends Service {

	private final static URL CQEMSBUSINESS_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.Cqemsbusiness.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.Cqemsbusiness.class.getResource(".");
			url = new URL(baseUrl,
					"http://115.28.134.167/cqemsbusiness.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://115.28.134.167/cqemsbusiness.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CQEMSBUSINESS_WSDL_LOCATION = url;
	}

	public Cqemsbusiness(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Cqemsbusiness() {
		super(CQEMSBUSINESS_WSDL_LOCATION, new QName("http://tempuri.org/",
				"cqemsbusiness"));
	}

	/**
	 * 
	 * @return returns CqemsbusinessSoap
	 */
	@WebEndpoint(name = "cqemsbusinessSoap")
	public CqemsbusinessSoap getCqemsbusinessSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"cqemsbusinessSoap"), CqemsbusinessSoap.class);
	}

	/**
	 * 
	 * @return returns CqemsbusinessSoap
	 */
	@WebEndpoint(name = "cqemsbusinessSoap12")
	public CqemsbusinessSoap getCqemsbusinessSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"cqemsbusinessSoap12"), CqemsbusinessSoap.class);
	}

}
