package com.wofu.ecommerce.sf.webServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IService", targetNamespace = "http://service.expressservice.integration.sf.com/")
public interface IService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.wofu.ecommerce.sf.webServiceClient.SfexpressService")
	@ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.wofu.ecommerce.sf.webServiceClient.SfexpressServiceResponse")
	public String sfexpressService(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
