package com.sf.integration.warehouse.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IOutsideToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/")
public interface IOutsideToLscmService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "yxToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.YxToLscmService")
	@ResponseWrapper(localName = "yxToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.YxToLscmServiceResponse")
	public String yxToLscmService(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "jyToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.JyToLscmService")
	@ResponseWrapper(localName = "jyToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.JyToLscmServiceResponse")
	public String jyToLscmService(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "outsideToLscmService", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.OutsideToLscmService")
	@ResponseWrapper(localName = "outsideToLscmServiceResponse", targetNamespace = "http://service.warehouse.integration.sf.com/", className = "com.sf.integration.warehouse.service.OutsideToLscmServiceResponse")
	public String outsideToLscmService(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
