package com.sf.integration.warehouse.service;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * OutsideToLscmServiceService service = new OutsideToLscmServiceService();
 * IOutsideToLscmService portType = service.getOutsideToLscmServicePort();
 * portType.yxToLscmService(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "OutsideToLscmServiceService", targetNamespace = "http://service.warehouse.integration.sf.com/", wsdlLocation = "http://219.134.187.154:9154/bsp-wms/ws/OutsideToLscmServiceImpl?wsdl")
public class OutsideToLscmServiceService extends Service {

	private final static URL OUTSIDETOLSCMSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.sf.integration.warehouse.service.OutsideToLscmServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.sf.integration.warehouse.service.OutsideToLscmServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://219.134.187.154:9154/bsp-wms/ws/OutsideToLscmServiceImpl?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://219.134.187.154:9154/bsp-wms/ws/OutsideToLscmServiceImpl?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		OUTSIDETOLSCMSERVICESERVICE_WSDL_LOCATION = url;
	}

	public OutsideToLscmServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public OutsideToLscmServiceService() {
		super(OUTSIDETOLSCMSERVICESERVICE_WSDL_LOCATION, new QName(
				"http://service.warehouse.integration.sf.com/",
				"OutsideToLscmServiceService"));
	}

	/**
	 * 
	 * @return returns IOutsideToLscmService
	 */
	@WebEndpoint(name = "OutsideToLscmServicePort")
	public IOutsideToLscmService getOutsideToLscmServicePort() {
		return super.getPort(new QName(
				"http://service.warehouse.integration.sf.com/",
				"OutsideToLscmServicePort"), IOutsideToLscmService.class);
	}

}
